container:
  image: cirrusci/flutter:latest

test_task:
  upgrade_script:
    #- flutter channel master
    #- flutter upgrade
    
  create_device_script:
    echo no | avdmanager create avd --force
        -n test
        -k "system-images;android-28;default;default"
  
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
        -avd test
        -no-audio
        -no-window
  
  wait_for_emulator_script:
    - adb wait-for-device
  
  pub_cache:
    folder: ~/.pub-cache
    
  test_script: flutter test
  
