container:
  image: cirrusci/flutter:latest

test_task:
  upgrade_script:
    #- flutter channel master
    #- flutter upgrade
    - cd $ANDROID_HOME/tools/bin
    - ls -l
    - ./sdkmanager "system-images;android-28;default;x86_64"
    
  create_device_script:
    echo no | avdmanager create avd --force
        -n test
        -k "system-images;android-28;default;x86_64"
        
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
        -avd test
        -no-audio
        -no-window
  
  wait_for_emulator_script:
    #- adb wait-for-device
  
  pub_cache:
    folder: ~/.pub-cache
    
  test_script:
    - flutter clean
    - pub cache repair
    - pub upgrade
    - pub deps    
    - flutter packages get
    - flutter test
  
