container:
  #dockerfile: .ci/Dockerfile  
  image: cirrusci/flutter:latest

test_task:
  upgrade_script:
    #- flutter clean  
    #- flutter channel master
    #- flutter upgrade
    - cd $ANDROID_HOME/tools/bin
    - ls -l
    - ./sdkmanager "system-images;android-22;google_apis;armeabi-v7a"
    ##- ./sdkmanager --list
    
  create_device_script:
    echo no | avdmanager create avd --force
        -n test
        -k "system-images;android-22;google_apis;armeabi-v7a"
        
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
        -avd test
        -no-audio
        -no-window
  
  wait_for_emulator_script:
    #- adb wait-for-device
  
  pub_cache:
    folder: ~/.pub-cache
    
  test_script:
    - pwd
    - ls -l
    - flutter clean
    #- pub cache repair
    - flutter packages upgrade 
    #- flutter packages get
    - pub deps    
    - flutter test
  
